server:
  port: 9006
#注册到Eureka服务中心
eureka:
  client:
    service-url:
      # 注册到集群，就把多个Eurekaserver地址使用逗号连接起来即可；注册到单实例（非集群模式），那就写一个就ok
      defaultZone: http://LagouCloudEurekaServerA:8761/eureka,http://LagouCloudEurekaServerB:8762/eureka
  instance:
    prefer-ip-address: true  #服务实例中显示ip，而不是显示主机名（兼容老的eureka版本）
    # 实例名称： 192.168.1.103:lagou-service-resume:8080，我们可以自定义它
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@

spring:
  application:
    name: lagou-cloud-configserver
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/struggle_ly/spring-cloud-config-repo.git #配置git服务地址
          username: 15580319228 #配置git用户名
          password: HH2022090920010909 #配置git密码
          search-paths:
            - spring-cloud-config-repo
      # 读取分支
      label: lagou-login-config
  rabbitmq:
    host: 175.178.27.134
    port: 5672
    username: guest
    password: guest
