server:
  port: 8762
spring:
  application:
    name: lagou-cloud-eureka-server

eureka:
  instance:
    # 当前eureka实例的主机名称
    hostname: LagouCloudEurekaServerB
  client:
    service-url:
      # 客户端与Eureka server交互的地址，EurekaServer相对于其他server来说也是client
      # 集群模式下，需要写其他server的地址，多个使用逗号拼接即可
      defaultZone: http://LagouCloudEurekaServerA:8761/eureka/
      # 是否注册到eureka中， 自己就是serve不需要注册自己，集群模式下设置为true
    register-with-eureka: true
    # 自己就是服务不需要从Eureka Server获取服务信息，默认为true， 这里设置为false
    fetch-registry: true
